-- Enable PostGIS for geospatial queries
CREATE EXTENSION IF NOT EXISTS postgis;

-- ==========================================
-- DOMAIN 1: OPERATIONAL ENTITIES
-- ==========================================

CREATE TABLE couriers (
    courier_id VARCHAR(50) PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    register_date DATE NOT NULL DEFAULT CURRENT_DATE,
    vehicle_type VARCHAR(50)
);

CREATE TABLE clients (
    client_id VARCHAR(50) PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone VARCHAR(50)
);

-- ==========================================
-- DOMAIN 2: LOGISTICS ASSIGNMENT (PIVOT ARCHITECTURE)
-- ==========================================

CREATE TABLE client_commande_detail (
    commande_id SERIAL PRIMARY KEY,
    client_id VARCHAR(50) REFERENCES clients(client_id) ON DELETE CASCADE,
    weight_kg DECIMAL(10,2),
    window_start TIMESTAMP,
    window_end TIMESTAMP,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL
);

CREATE TABLE daily_manifest (
    manifest_id VARCHAR(50) PRIMARY KEY,
    courier_id VARCHAR(50) REFERENCES couriers(courier_id) ON DELETE CASCADE,
    date DATE NOT NULL,
    status VARCHAR(50) DEFAULT 'PLANNED' CHECK (status IN ('PLANNED', 'IN_TRANSIT', 'COMPLETED', 'DELAYED')),
    ai_recommendation JSONB DEFAULT NULL
);

CREATE TABLE manifest_stops (
    stop_id SERIAL PRIMARY KEY,
    manifest_id VARCHAR(50) REFERENCES daily_manifest(manifest_id) ON DELETE CASCADE,
    commande_id INT REFERENCES client_commande_detail(commande_id) ON DELETE CASCADE,
    delivery_order INT NOT NULL,
    delivery_status VARCHAR(50) DEFAULT 'PENDING' CHECK (delivery_status IN ('PENDING', 'DELIVERED', 'FAILED', 'SKIPPED')),
    actual_delivery_time TIMESTAMP DEFAULT NULL
);

-- ==========================================
-- DOMAIN 3: SPATIAL DATA (CITY TOPOLOGY)
-- ==========================================

CREATE TABLE segments (
    segment_id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(255),
    start_lat FLOAT NOT NULL,
    start_lon FLOAT NOT NULL,
    end_lat FLOAT NOT NULL,
    end_lon FLOAT NOT NULL,
    geom GEOMETRY(LineString, 4326)
);

CREATE INDEX segments_geom_idx ON segments USING GIST (geom);

-- ==========================================
-- DOMAIN 4: TELEMETRY & AI (REDIS-WORKER FED)
-- ==========================================

CREATE TABLE segment_telemetry (
    telemetry_id SERIAL PRIMARY KEY,
    segment_id VARCHAR(50) REFERENCES segments(segment_id) ON DELETE CASCADE,
    courier_id VARCHAR(50) REFERENCES couriers(courier_id) ON DELETE CASCADE,
    entry_time TIMESTAMP NOT NULL,
    exit_time TIMESTAMP NOT NULL,
    average_speed FLOAT NOT NULL
);

CREATE TABLE environmental_snapshots (
    snapshot_id SERIAL PRIMARY KEY,
    segment_id VARCHAR(50) REFERENCES segments(segment_id) ON DELETE CASCADE,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    temperature_c INT,
    weather_condition VARCHAR(100)
);

CREATE TABLE traffic_snapshots (
    traffic_snapshot_id SERIAL PRIMARY KEY,
    segment_id VARCHAR(50) REFERENCES segments(segment_id) ON DELETE CASCADE,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    traffic_level VARCHAR(50),      -- e.g., 'LIGHT', 'MODERATE', 'HEAVY', 'GRIDLOCK'
    incident_reported BOOLEAN DEFAULT FALSE
);

-- ==========================================
-- DOMAIN 5: GATEWAY VIEWS
-- ==========================================
CREATE OR REPLACE VIEW active_courier_stops AS
SELECT
    ms.stop_id::text AS stop_id,
    ccd.lat          AS latitude,
    ccd.lon          AS longitude,
    ms.delivery_order,
    ccd.window_start AS time_window_open,
    ccd.window_end   AS time_window_close,
    ccd.weight_kg    AS package_weight_kg,
    dm.manifest_id,
    dm.courier_id,
    ms.delivery_status AS status
FROM manifest_stops ms
JOIN daily_manifest         dm  ON ms.manifest_id = dm.manifest_id
JOIN client_commande_detail ccd ON ms.commande_id  = ccd.commande_id;

-- ==========================================
-- INITIAL MOCK DATA SEEDING (Sivas Coordinates)
-- ==========================================
-- Password: 'password123' — hash generated by bcryptjs inside container (rounds=10)
INSERT INTO couriers (courier_id, first_name, last_name, email, password, vehicle_type) 
VALUES ('DRV-884', 'John', 'Doe', 'johndoe@smartlogistics.com', '$2a$10$0qO50EutX1h.ojzwFnptHOicHs4m3Qg45YK6ll2EoYxytSqU6MYHy', 'Van')
ON CONFLICT (courier_id) DO NOTHING;

INSERT INTO clients (client_id, first_name, last_name, email, phone) VALUES
('CLI-001', 'Ali', 'Yilmaz', 'ali.yilmaz@test.com', '+90 346 111 2233'),
('CLI-002', 'Ayse', 'Demir', 'ayse.demir@test.com', '+90 346 222 3344'),
('CLI-003', 'Mehmet', 'Kaya', 'mehmet.kaya@test.com', '+90 346 333 4455')
ON CONFLICT (client_id) DO NOTHING;

INSERT INTO client_commande_detail (commande_id, client_id, weight_kg, window_start, window_end, lat, lon) VALUES 
(1, 'CLI-001', 5.5, CURRENT_DATE + TIME '12:00:00', CURRENT_DATE + TIME '14:00:00', 39.750, 37.015),
(2, 'CLI-002', 2.0, CURRENT_DATE + TIME '14:30:00', CURRENT_DATE + TIME '16:00:00', 39.755, 37.020),
(3, 'CLI-003', 15.0, CURRENT_DATE + TIME '17:00:00', CURRENT_DATE + TIME '19:00:00', 39.760, 37.010)
ON CONFLICT (commande_id) DO NOTHING;

INSERT INTO daily_manifest (manifest_id, courier_id, date, status) VALUES 
('MANIFEST-TODAY', 'DRV-884', CURRENT_DATE, 'PLANNED')
ON CONFLICT (manifest_id) DO NOTHING;

INSERT INTO manifest_stops (stop_id, manifest_id, commande_id, delivery_order, delivery_status) VALUES 
(1, 'MANIFEST-TODAY', 1, 1, 'PENDING'),
(2, 'MANIFEST-TODAY', 2, 2, 'PENDING'),
(3, 'MANIFEST-TODAY', 3, 3, 'PENDING')
ON CONFLICT (stop_id) DO UPDATE SET delivery_status = 'PENDING';
